### ISSUE TITLE
singleSpa with angularcli and react approach

### ISSUE THREAD

**Issue by orlandodemauro** [orlandodemauro/single-spa-react-angularCli#1]
@robinComa  @joeldenning 

Hi guys,

First of all sorry to bother you, but I thought that both of you could help me with suggestions about the prototype that I´m creating.

The project is based on the ideas behind

[https://github.com/me-12/single-spa-portal-example](https://github.com/me-12/single-spa-portal-example)
and 
[https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples)

I would like to see what do you think about the different ideas and approaches that I proposed in my repo:

1. **dynamic app configuration: easily configure the children app.**
https://github.com/orlandodemauro/single-spa-react-angularCli/blob/7181dfc0853a0d1e108aeb6f66c00c399849a4a3/src/main.js#L9-L29

2 **the apps should be deployed separately.** for this reason the loader.js should be bundled with the angularCli app. I created a simple webpack config file that bundle the loader.js creating the lib/loader.js that is added to the angular-cli config file as assets. In the main app I import the bundle using SystemJs

https://github.com/orlandodemauro/single-spa-react-angularCli/blob/7181dfc0853a0d1e108aeb6f66c00c399849a4a3/src/app2/webpack.config.js

3 **run the apps in production mode**: the bundles names in production mode could be different from the bundles names generated in dev mode for this reason the scripts array in the loader.js cannot be hardcoded. I created a script called scripts_list_creator that run after that the angularCli build is complete that: get the bundles name in the dist folder, sort the array with the bundle list (the angular-cli bundles need to be loaded in a specific order), save the list in lib/bundle_list.json file. 
https://github.com/orlandodemauro/single-spa-react-angularCli/blob/7181dfc0853a0d1e108aeb6f66c00c399849a4a3/src/app2/scripts_list_creator.js

@robinComa  would be great to be able to pass customProperties into the child application, I saw your reply about it in an issue and I want to thank you for your effort and help.

What do you think about this 3 approaches? Sorry again to bother.

Thanks a milion

**Comment by robinComa** [comment]
Hello @orlandodemauro 

Happy to see your work, I've the same objectives for the future months.

I would like to create a similar thing to generate the loader because I dislike the hardcoded scripts, but I have no times to do this for the moment. I think read the generated index.html to keep the order generated by angular, and read the dist folder to add the lazy-loaded modules. I have an issue to do that : I would like to remove the  --output-hashing=media to avoid browser caching issues on portal and if I do this, I don't know the way to retreive the lazy loaded module.js (maybe the scripts inside /dist and not declare in index.html)
see : [https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/src/loaders/home.js#L14](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/src/loaders/home.js#L14)
This work is the job of the app project and not the portal, so I agree with you the generated loader should be outside the portal : inside the projet. I think it will be a postBuild npm task

I want to use SystemJS to load dynamically apps like you

For your information you can update to 0.2.3 the single spa angular cli to remove the registermain application (no single spa standard), now it is like this and that's works better : 

```
registerApplication('menu', import('./loaders/menu.js'), singleSpaAngularCliRouter.hashPrefix('/**'));
registerApplication('home', import('./loaders/home.js'), singleSpaAngularCliRouter.hashPrefix('/home', true));
registerApplication('app1', import('./loaders/app1.js'), singleSpaAngularCliRouter.hashPrefix('/app1'));
registerApplication('help', import('./loaders/help.js'), singleSpaAngularCliRouter.hasParameter('help', 'open'));

start();
```

Note : only standard registerApplication, hasParameter('help', 'open'), [uses of css files and adding a name for your apps](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#add-an-angular-cli-apps), name of the application and passing custom properties (breaking change singleSpaAngularCliPlatform.mount first args is now the application name) : 

```
singleSpaAngularCliPlatform.mount('app1', Router).subscribe(({ props, attachUnmount }) => {
  platformBrowserDynamic().bootstrapModule(AppModule).then((module) => {
    attachUnmount(module);
    // Do something with props if you want
    // Ex : module.instance.setSomething(...)
  });
});
```

**Comment by orlandodemauro** [comment]
hello @robinComa,

thank you for you interest in this repo. this is the old version of my code, the new code is available at https://github.com/orlandodemauro/microfrontends-spa-portal where I´m using the last version of the single-spa-angular-cli and I removed the registermain 

there is no way, that i know, to get the bundles list in dev mode. for this reason I´m using an hardcoded bundle list in dev mode and when in production I´m using a post build script that is generating the prod bundles list. I´m using regex to get the bundle names with has. you can find the loader here

https://github.com/orlandodemauro/microfrontends-spa-portal/blob/eab176ac2a931c26a3ce60e9ab5c7e856e051b5e/src/app2/loader.js#L1

and the script here

https://github.com/orlandodemauro/microfrontends-spa-portal/blob/eab176ac2a931c26a3ce60e9ab5c7e856e051b5e/src/app2/scripts_list_creator.js#L1


please let me know if I can help with something.

**Comment by orlandodemauro** [comment]
hello @robinComa ,

any reason why the singleSpaAngularCliPlatform.mount first args is now the application name?

**Comment by internettrans** [comment]
@orlandodemauro apologies for the slow response here -- this one got lost in my notifications.

Have you been able to make progress on your three goals? Hopefully the recent changes to single-spa and single-spa-angular-cli have straightened some of the problems out. How is independent deployability coming along? That one is many times the hardest.

**Comment by orlandodemauro** [comment]
@joeldenning np at all and again thanks for your help. yes the recent changes helped me a lot and I was able to implement the independent deployment of the angular-cli apps. you can find the code here https://github.com/orlandodemauro/microfrontends-spa-portal.

the main ideas behind are:

1. use a shared redux store between the apps (I copied the idea from one of the repo in single-spa)
2. separate deployments with systemjs
3. use a global eventBus
4. configurable main.js ( with a app-structure.json)

It is tricky to achieve separate deployment with angular-cli, to do it I did:

1. create a script that read the bundles created in the dist folder
2. order the list of the bundle names (inline.bundle first and main.bundle last).
3. import the new list in the loader.js and bundle it using webpack
4. pass the APP_BASE_HREF as custom property to the child app

@robinComa if you need an help to implement it in the angular-cli-example repo please let me know and I´ll find sometime this week-end

@robinComa @joeldenning the only issue that i have is that in dev mode there is no way, that i know, to get the bundle list (webpack dev-server uses on-memory bundles), for this reason I still need an hard-coded bundle list in dev-mode. any suggestions?

**Comment by robinComa** [comment]
@orlandodemauro if you want I could work on these topics : 
- Read bundle list (index.html for prod mode, and maybe a request on http://localhost:4200 to read the index.html of the dev mode) to generate bundle list
- To acheive it, I have to fix the load of lazy loading modules (now it is loaded at start and it is bad) my issue with this point is that the request is done with a APP_BASE_HREF / (why do you have to work on APP_BASE_HREF ? what is your issue?)
- So I have to work on APP_BASE_HREF too

I hope I could work on it before the end of the weekend.

**Comment by orlandodemauro** [comment]
@robinComa when the app is loaded with single-spa it will loaded for example using localhost:8080/app, and the app is running on the server localhost:4200 with APP_BASE_HREF = /.

lets assume that you have a button that redirect to /active, when you click it will redirect to localhost:8080/active and not localhost:8080/app/active

**Comment by robinComa** [comment]
To avoid it, I use to declare this "namespace" on the child apps like (path: 'home') : 

```
const routes: Routes = [
    {
        path: 'home',
        children: [
            { path: 'route1', component: Route1Component },
            { path: 'route2', loadChildren: 'app/route2module/route2-routing.module#Route2RoutingModule' }
        ]
    }, {
        path: '**',
        redirectTo: 'home'
    }
];

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    providers: [
        { provide: LocationStrategy, useClass: HashLocationStrategy },
        { provide: APP_BASE_HREF, useValue: '/' }
    ],
    exports: [RouterModule]
})
export class AppRoutingModule { }
```
Is it not good according to you? Do you prefer to have 0 impact inside the child application?

**Comment by robinComa** [comment]
@orlandodemauro I decide to change the first args to the name of the single spa application because according to me this is a better abstraction than the root tag of the cli apps

**Comment by orlandodemauro** [comment]
@robinComa in this way you force the parent to render the app using the path home, in this way the route cannot be decided by the parent

**Comment by robinComa** [comment]
@orlandodemauro it is not the path, it is the name of the single spa app or I'm wrong?

**Comment by robinComa** [comment]
@orlandodemauro I acheive the dynamic styles and scripts loading : 
[single-spa-angular-cli 0.3.1](https://www.npmjs.com/package/single-spa-angular-cli)
You have to see :
[the new loader](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#create-an-angular-cli-loader)
[the way to run cli app in dev mode](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#serve-your-angular-app-project-for-developement-mode)

I broke something : the lazy loading of sub angular module, I will work on it very soon

I choose the read index.html strategy to not hard coded something : [here](https://github.com/PlaceMe-SAS/single-spa-angular-cli/blob/master/src/loader/index.ts#L24)

Let me know if it is works now!

**Comment by robinComa** [comment]
@orlandodemauro 
I manage to deal with assets like images and lazy loaded bundle thanks to the APP_BASE_HREF.
See to new [example](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples#configure-a-proxy-to-use-the-cli-dev-mode-app)

I decide to build the app at the same place than the APP_BASE_HREF to avoid issues : [-op opts](https://github.com/PlaceMe-SAS/single-spa-angular-cli-examples/blob/master/package.json#L9)

**Comment by orlandodemauro** [comment]
@robinComa notginh to say other than thanks :) this new version let me remove all my scripts to get the bundle list. 

the only issue that we have is still get the APP_BASE_HREF from the parent or from a config file, this because in a "self deployable" environment the child app doesn´t know which route the parent is using to render it.

thanks again for your work, i´ll continue to do some test and let you know if i´ll find something

**Comment by orlandodemauro** [comment]
@robinComa  could you please explain how to use this new version with systemJs? how you register a children app when it is not in the same source code of the parent as in your example? I tried to understand it but with no success yet. maybe i need more coffe today

**Comment by orlandodemauro** [comment]
@robinComa  ok nevermind. to load the app using systemJs we need to pass the url in the 


    {
        "name": "app2",
        "selector": "app2-root",
        "outputPath": "http://localhost/4203",
        "matchRoute": "/app2"
    },

could you please confirm it?

**Comment by robinComa** [comment]
Happy to see your feeling @orlandodemauro with this new version! Yes the url is the output path.
I agree with you for the configuration of the app base ref. I have no clean idea for the moment (only dirty) but I want to fix it for the future

**Comment by orlandodemauro** [comment]
@robinComa  I´ll let you know if I´ll find something. thanks again
